<?php
require_once __DIR__ . '/../config/database.php';

// Array of common plants data
$common_plants = [
    // Indoor Plants
    [
        'name' => 'Aloe Vera',
        'scientific_name' => 'Aloe barbadensis miller',
        'description' => 'A succulent plant known for its medicinal properties and gel-filled leaves. Popular for its healing properties and easy care requirements.',
        'care_instructions' => 'Place in bright, indirect sunlight. Water deeply but infrequently, allowing soil to dry between waterings. Use well-draining soil mix.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Low - water every 2-3 weeks',
        'temperature_range' => '55-80°F (13-27°C)',
        'humidity_requirements' => 'Average indoor humidity',
        'soil_type' => 'Well-draining cactus/succulent mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '1-2 feet',
        'toxicity_level' => 'Non-toxic to humans, toxic to pets'
    ],
    [
        'name' => 'Snake Plant',
        'scientific_name' => 'Sansevieria trifasciata',
        'description' => 'A hardy, low-maintenance plant known for its upright, sword-like leaves. Perfect for beginners and can survive in various light conditions.',
        'care_instructions' => 'Water sparingly, allowing soil to dry between waterings. Can tolerate low light but prefers indirect bright light.',
        'light_requirements' => 'Low to bright indirect light',
        'water_requirements' => 'Low - water every 2-3 weeks',
        'temperature_range' => '60-85°F (15-29°C)',
        'humidity_requirements' => 'Average indoor humidity',
        'soil_type' => 'Well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Slow',
        'mature_height' => '2-4 feet',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Spider Plant',
        'scientific_name' => 'Chlorophytum comosum',
        'description' => 'A popular houseplant known for its arching leaves and ability to produce plantlets. Great air-purifying plant that\'s easy to care for.',
        'care_instructions' => 'Keep in bright indirect light. Water when top soil is dry. Prefers slightly moist soil but can tolerate some drought.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Moderate - water when soil is dry',
        'temperature_range' => '65-80°F (18-27°C)',
        'humidity_requirements' => 'Average to high humidity',
        'soil_type' => 'Well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Fast',
        'mature_height' => '1-2 feet',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Peace Lily',
        'scientific_name' => 'Spathiphyllum',
        'description' => 'An elegant plant known for its white flowers and glossy leaves. Excellent air-purifying qualities and beautiful blooms.',
        'care_instructions' => 'Keep in low to bright indirect light. Water when soil surface feels dry. Mist leaves occasionally.',
        'light_requirements' => 'Low to bright indirect light',
        'water_requirements' => 'Moderate - keep soil moist',
        'temperature_range' => '65-80°F (18-27°C)',
        'humidity_requirements' => 'High humidity preferred',
        'soil_type' => 'Rich, well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '1-4 feet',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Pothos',
        'scientific_name' => 'Epipremnum aureum',
        'description' => 'A versatile trailing plant with heart-shaped leaves. Known for its ability to thrive in various conditions and purify air.',
        'care_instructions' => 'Grow in bright indirect light. Water when soil is dry. Can be trained to climb or trail.',
        'light_requirements' => 'Low to bright indirect light',
        'water_requirements' => 'Moderate - water when soil is dry',
        'temperature_range' => '60-85°F (15-29°C)',
        'humidity_requirements' => 'Average indoor humidity',
        'soil_type' => 'Well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Fast',
        'mature_height' => '6-10 feet (trailing)',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Philodendron',
        'scientific_name' => 'Philodendron hederaceum',
        'description' => 'A popular climbing plant with heart-shaped leaves. Known for its adaptability and beautiful foliage.',
        'care_instructions' => 'Provide bright indirect light. Water when top soil is dry. Can be trained to climb or trail.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Moderate - water when soil is dry',
        'temperature_range' => '65-80°F (18-27°C)',
        'humidity_requirements' => 'High humidity preferred',
        'soil_type' => 'Rich, well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Fast',
        'mature_height' => '6-8 feet (climbing)',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'ZZ Plant',
        'scientific_name' => 'Zamioculcas zamiifolia',
        'description' => 'A hardy plant with glossy, dark green leaves. Known for its ability to survive in low light and drought conditions.',
        'care_instructions' => 'Tolerates low light. Water sparingly, allowing soil to dry completely between waterings.',
        'light_requirements' => 'Low to bright indirect light',
        'water_requirements' => 'Low - water every 2-3 weeks',
        'temperature_range' => '65-80°F (18-27°C)',
        'humidity_requirements' => 'Average indoor humidity',
        'soil_type' => 'Well-draining potting mix',
        'fertilizer_needs' => 'Quarterly',
        'growth_rate' => 'Slow',
        'mature_height' => '2-3 feet',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Fiddle Leaf Fig',
        'scientific_name' => 'Ficus lyrata',
        'description' => 'A popular indoor tree with large, violin-shaped leaves. Known for its dramatic appearance and statement-making presence.',
        'care_instructions' => 'Place in bright indirect light. Water when top soil is dry. Keep away from drafts.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Moderate - water when soil is dry',
        'temperature_range' => '65-75°F (18-24°C)',
        'humidity_requirements' => 'High humidity preferred',
        'soil_type' => 'Rich, well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '6-10 feet indoors',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Jade Plant',
        'scientific_name' => 'Crassula ovata',
        'description' => 'A succulent with thick, woody stems and oval-shaped leaves. Known for its tree-like appearance and longevity.',
        'care_instructions' => 'Place in bright indirect light. Water when soil is completely dry. Allow soil to dry between waterings.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Low - water every 2-3 weeks',
        'temperature_range' => '65-75°F (18-24°C)',
        'humidity_requirements' => 'Average indoor humidity',
        'soil_type' => 'Well-draining cactus/succulent mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Slow',
        'mature_height' => '2-3 feet',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Rubber Plant',
        'scientific_name' => 'Ficus elastica',
        'description' => 'A popular houseplant with large, glossy leaves. Known for its easy care and air-purifying qualities.',
        'care_instructions' => 'Place in bright indirect light. Water when top soil is dry. Wipe leaves occasionally to remove dust.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Moderate - water when soil is dry',
        'temperature_range' => '65-80°F (18-27°C)',
        'humidity_requirements' => 'Average to high humidity',
        'soil_type' => 'Well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '6-10 feet indoors',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Boston Fern',
        'scientific_name' => 'Nephrolepis exaltata',
        'description' => 'A classic fern with delicate, feathery fronds. Known for its lush appearance and air-purifying qualities.',
        'care_instructions' => 'Keep in bright indirect light. Maintain consistently moist soil. Mist regularly to increase humidity.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'High - keep soil moist',
        'temperature_range' => '60-75°F (15-24°C)',
        'humidity_requirements' => 'High humidity required',
        'soil_type' => 'Rich, well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '2-3 feet',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Monstera',
        'scientific_name' => 'Monstera deliciosa',
        'description' => 'Known as the Swiss Cheese Plant, famous for its large, glossy leaves with natural holes. A popular tropical plant.',
        'care_instructions' => 'Place in bright indirect light. Water when top soil is dry. Provide support for climbing.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Moderate - water when soil is dry',
        'temperature_range' => '65-85°F (18-29°C)',
        'humidity_requirements' => 'High humidity preferred',
        'soil_type' => 'Rich, well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '6-8 feet indoors',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Dracaena',
        'scientific_name' => 'Dracaena fragrans',
        'description' => 'A popular houseplant with long, arching leaves. Known for its air-purifying qualities and easy care.',
        'care_instructions' => 'Place in bright indirect light. Water when soil is dry. Remove brown leaf tips as needed.',
        'light_requirements' => 'Low to bright indirect light',
        'water_requirements' => 'Moderate - water when soil is dry',
        'temperature_range' => '65-80°F (18-27°C)',
        'humidity_requirements' => 'Average indoor humidity',
        'soil_type' => 'Well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Slow',
        'mature_height' => '4-6 feet indoors',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Areca Palm',
        'scientific_name' => 'Dypsis lutescens',
        'description' => 'A graceful palm with feathery, arching fronds. Known for its tropical appearance and air-purifying qualities.',
        'care_instructions' => 'Place in bright indirect light. Keep soil consistently moist. Mist regularly.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Moderate - keep soil moist',
        'temperature_range' => '65-75°F (18-24°C)',
        'humidity_requirements' => 'High humidity preferred',
        'soil_type' => 'Rich, well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '6-8 feet indoors',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'English Ivy',
        'scientific_name' => 'Hedera helix',
        'description' => 'A versatile climbing vine with small, pointed leaves. Known for its ability to purify air and adapt to various conditions.',
        'care_instructions' => 'Grow in bright indirect light. Water when soil is dry. Can be trained to climb or trail.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Moderate - water when soil is dry',
        'temperature_range' => '50-70°F (10-21°C)',
        'humidity_requirements' => 'Average to high humidity',
        'soil_type' => 'Well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Fast',
        'mature_height' => '6-8 feet (climbing)',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Dieffenbachia',
        'scientific_name' => 'Dieffenbachia seguine',
        'description' => 'A tropical plant with large, variegated leaves. Known for its striking appearance and easy care requirements.',
        'care_instructions' => 'Place in bright indirect light. Water when top soil is dry. Keep away from pets and children.',
        'light_requirements' => 'Low to bright indirect light',
        'water_requirements' => 'Moderate - water when soil is dry',
        'temperature_range' => '65-80°F (18-27°C)',
        'humidity_requirements' => 'High humidity preferred',
        'soil_type' => 'Rich, well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '3-5 feet',
        'toxicity_level' => 'Highly toxic to pets and humans'
    ],
    [
        'name' => 'Croton',
        'scientific_name' => 'Codiaeum variegatum',
        'description' => 'A colorful plant with vibrant, variegated leaves. Known for its striking appearance and tropical feel.',
        'care_instructions' => 'Place in bright indirect light. Keep soil consistently moist. Mist regularly.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Moderate - keep soil moist',
        'temperature_range' => '60-80°F (15-27°C)',
        'humidity_requirements' => 'High humidity required',
        'soil_type' => 'Rich, well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Slow',
        'mature_height' => '3-6 feet',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'Begonia',
        'scientific_name' => 'Begonia spp.',
        'description' => 'A diverse group of plants known for their beautiful flowers and foliage. Popular for indoor and outdoor gardens.',
        'care_instructions' => 'Place in bright indirect light. Water when soil is dry. Avoid getting water on leaves.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Moderate - water when soil is dry',
        'temperature_range' => '65-75°F (18-24°C)',
        'humidity_requirements' => 'High humidity preferred',
        'soil_type' => 'Rich, well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '1-2 feet',
        'toxicity_level' => 'Toxic to pets'
    ],
    [
        'name' => 'African Violet',
        'scientific_name' => 'Saintpaulia ionantha',
        'description' => 'A popular houseplant known for its delicate flowers and fuzzy leaves. Blooms throughout the year.',
        'care_instructions' => 'Place in bright indirect light. Water from bottom. Keep leaves dry.',
        'light_requirements' => 'Bright indirect light',
        'water_requirements' => 'Moderate - keep soil moist',
        'temperature_range' => '65-75°F (18-24°C)',
        'humidity_requirements' => 'High humidity preferred',
        'soil_type' => 'Special African violet mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Slow',
        'mature_height' => '6-8 inches',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Calathea',
        'scientific_name' => 'Calathea makoyana',
        'description' => 'A stunning plant with patterned leaves that move in response to light. Known for its unique foliage.',
        'care_instructions' => 'Place in bright indirect light. Keep soil consistently moist. Mist regularly.',
        'light_requirements' => 'Low to bright indirect light',
        'water_requirements' => 'Moderate - keep soil moist',
        'temperature_range' => '65-80°F (18-27°C)',
        'humidity_requirements' => 'High humidity required',
        'soil_type' => 'Rich, well-draining potting mix',
        'fertilizer_needs' => 'Monthly during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '1-2 feet',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Basil',
        'scientific_name' => 'Ocimum basilicum',
        'description' => 'A popular culinary herb with fragrant leaves. Essential in many cuisines, especially Italian dishes.',
        'care_instructions' => 'Place in full sun. Water regularly to keep soil moist. Pinch off flower buds to promote leaf growth.',
        'light_requirements' => 'Full sun',
        'water_requirements' => 'Moderate - keep soil moist',
        'temperature_range' => '65-85°F (18-29°C)',
        'humidity_requirements' => 'Average humidity',
        'soil_type' => 'Well-draining, rich soil',
        'fertilizer_needs' => 'Light monthly feeding',
        'growth_rate' => 'Fast',
        'mature_height' => '1-2 feet',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Rosemary',
        'scientific_name' => 'Salvia rosmarinus',
        'description' => 'An aromatic evergreen herb with needle-like leaves. Used in cooking and as an ornamental plant.',
        'care_instructions' => 'Place in full sun. Allow soil to dry between waterings. Prune regularly to maintain shape.',
        'light_requirements' => 'Full sun',
        'water_requirements' => 'Low - drought tolerant',
        'temperature_range' => '65-70°F (18-21°C)',
        'humidity_requirements' => 'Low humidity preferred',
        'soil_type' => 'Well-draining, sandy soil',
        'fertilizer_needs' => 'Light feeding in spring',
        'growth_rate' => 'Slow',
        'mature_height' => '2-4 feet',
        'toxicity_level' => 'Toxic to pets in large quantities'
    ],
    [
        'name' => 'Tomato',
        'scientific_name' => 'Solanum lycopersicum',
        'description' => 'A popular garden vegetable producing juicy, red fruits. Available in many varieties and sizes.',
        'care_instructions' => 'Place in full sun. Water deeply and regularly. Support with cages or stakes.',
        'light_requirements' => 'Full sun',
        'water_requirements' => 'High - consistent moisture',
        'temperature_range' => '65-85°F (18-29°C)',
        'humidity_requirements' => 'Moderate humidity',
        'soil_type' => 'Rich, well-draining soil',
        'fertilizer_needs' => 'Regular feeding during growing season',
        'growth_rate' => 'Fast',
        'mature_height' => '3-6 feet',
        'toxicity_level' => 'Leaves and stems toxic to pets'
    ],
    [
        'name' => 'Lettuce',
        'scientific_name' => 'Lactuca sativa',
        'description' => 'A leafy vegetable commonly used in salads. Available in many varieties with different textures and colors.',
        'care_instructions' => 'Place in partial shade to full sun. Keep soil consistently moist. Harvest outer leaves as needed.',
        'light_requirements' => 'Partial shade to full sun',
        'water_requirements' => 'Moderate - keep soil moist',
        'temperature_range' => '45-75°F (7-24°C)',
        'humidity_requirements' => 'Average humidity',
        'soil_type' => 'Rich, well-draining soil',
        'fertilizer_needs' => 'Light feeding every 2-3 weeks',
        'growth_rate' => 'Fast',
        'mature_height' => '6-12 inches',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Mint',
        'scientific_name' => 'Mentha spp.',
        'description' => 'A fast-growing herb with aromatic leaves. Used in cooking, beverages, and as a ground cover.',
        'care_instructions' => 'Place in partial shade to full sun. Keep soil moist. Plant in containers to control spread.',
        'light_requirements' => 'Partial shade to full sun',
        'water_requirements' => 'Moderate - keep soil moist',
        'temperature_range' => '55-70°F (13-21°C)',
        'humidity_requirements' => 'Average humidity',
        'soil_type' => 'Rich, moist soil',
        'fertilizer_needs' => 'Light monthly feeding',
        'growth_rate' => 'Very fast',
        'mature_height' => '1-2 feet',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Carrot',
        'scientific_name' => 'Daucus carota',
        'description' => 'A root vegetable known for its orange color and sweet taste. Rich in vitamins and minerals.',
        'care_instructions' => 'Plant in loose, well-draining soil. Keep soil consistently moist. Thin seedlings as needed.',
        'light_requirements' => 'Full sun',
        'water_requirements' => 'Moderate - consistent moisture',
        'temperature_range' => '55-75°F (13-24°C)',
        'humidity_requirements' => 'Average humidity',
        'soil_type' => 'Loose, sandy soil',
        'fertilizer_needs' => 'Light feeding at planting',
        'growth_rate' => 'Moderate',
        'mature_height' => '6-12 inches above ground',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Bell Pepper',
        'scientific_name' => 'Capsicum annuum',
        'description' => 'A sweet pepper variety producing large, bell-shaped fruits. Available in various colors.',
        'care_instructions' => 'Place in full sun. Water regularly. Support plants as they grow.',
        'light_requirements' => 'Full sun',
        'water_requirements' => 'Moderate - consistent moisture',
        'temperature_range' => '70-85°F (21-29°C)',
        'humidity_requirements' => 'Moderate humidity',
        'soil_type' => 'Rich, well-draining soil',
        'fertilizer_needs' => 'Regular feeding during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '2-3 feet',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Cucumber',
        'scientific_name' => 'Cucumis sativus',
        'description' => 'A vining plant producing elongated, green fruits. Popular in salads and pickling.',
        'care_instructions' => 'Place in full sun. Water regularly. Provide trellis for climbing varieties.',
        'light_requirements' => 'Full sun',
        'water_requirements' => 'High - consistent moisture',
        'temperature_range' => '65-75°F (18-24°C)',
        'humidity_requirements' => 'Moderate humidity',
        'soil_type' => 'Rich, well-draining soil',
        'fertilizer_needs' => 'Regular feeding during growing season',
        'growth_rate' => 'Fast',
        'mature_height' => 'Vining - 6-8 feet',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Spinach',
        'scientific_name' => 'Spinacia oleracea',
        'description' => 'A leafy green vegetable rich in nutrients. Used in salads, cooking, and smoothies.',
        'care_instructions' => 'Place in partial shade to full sun. Keep soil consistently moist. Harvest leaves as needed.',
        'light_requirements' => 'Partial shade to full sun',
        'water_requirements' => 'Moderate - keep soil moist',
        'temperature_range' => '50-70°F (10-21°C)',
        'humidity_requirements' => 'Average humidity',
        'soil_type' => 'Rich, well-draining soil',
        'fertilizer_needs' => 'Light feeding every 2-3 weeks',
        'growth_rate' => 'Fast',
        'mature_height' => '6-12 inches',
        'toxicity_level' => 'Non-toxic to pets'
    ],
    [
        'name' => 'Strawberry',
        'scientific_name' => 'Fragaria × ananassa',
        'description' => 'A perennial plant producing sweet, red fruits. Popular in gardens and containers.',
        'care_instructions' => 'Place in full sun. Keep soil consistently moist. Remove runners to promote fruit production.',
        'light_requirements' => 'Full sun',
        'water_requirements' => 'Moderate - consistent moisture',
        'temperature_range' => '60-80°F (16-27°C)',
        'humidity_requirements' => 'Moderate humidity',
        'soil_type' => 'Rich, well-draining soil',
        'fertilizer_needs' => 'Regular feeding during growing season',
        'growth_rate' => 'Moderate',
        'mature_height' => '6-8 inches',
        'toxicity_level' => 'Non-toxic to pets'
    ],
];

try {
    // Create table if it doesn't exist
    $pdo->exec("CREATE TABLE IF NOT EXISTS common_plants (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        scientific_name VARCHAR(100),
        description TEXT NOT NULL,
        care_instructions TEXT,
        light_requirements VARCHAR(100),
        water_requirements VARCHAR(100),
        temperature_range VARCHAR(100),
        humidity_requirements VARCHAR(100),
        soil_type VARCHAR(100),
        fertilizer_needs VARCHAR(100),
        growth_rate VARCHAR(50),
        mature_height VARCHAR(50),
        toxicity_level VARCHAR(50),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )");

    // Clear existing data
    $pdo->exec("TRUNCATE TABLE common_plants");

    // Prepare insert statement
    $stmt = $pdo->prepare("INSERT INTO common_plants (
        name, scientific_name, description, care_instructions,
        light_requirements, water_requirements, temperature_range,
        humidity_requirements, soil_type, fertilizer_needs,
        growth_rate, mature_height, toxicity_level
    ) VALUES (
        :name, :scientific_name, :description, :care_instructions,
        :light_requirements, :water_requirements, :temperature_range,
        :humidity_requirements, :soil_type, :fertilizer_needs,
        :growth_rate, :mature_height, :toxicity_level
    )");

    // Insert each plant
    foreach ($common_plants as $plant) {
        $stmt->execute($plant);
    }

    echo "Common plants data populated successfully!";
} catch (PDOException $e) {
    echo "Error: " . $e->getMessage();
}
?> 